# Generated by Django 5.2.3 on 2025-06-14 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_cliente_creado_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ciudad",
            field=models.CharField(default="Ciudad no especificada", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="correo",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=20),
        ),
    ]
