# Generated by Django 5.2.3 on 2025-06-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_venta_tipo_pago"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="usuario",
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="estado",
            field=models.CharField(
                choices=[("activa", "Activa"), ("anulada", "Anulada")],
                default="activa",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="numero_factura",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
