# Generated by Django 5.2.3 on 2025-06-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_venta_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="ciudad",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="creado_por",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="estado",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
