# Generated by Django 5.2.3 on 2025-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_abono_usuario_alter_abono_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="tipo_pago",
            field=models.CharField(
                choices=[
                    ("contado", "Contado"),
                    ("credito", "Crédito"),
                    ("transferencia", "Transferencia"),
                    ("garantia", "Garantía"),
                ],
                default="contado",
                max_length=15,
            ),
        ),
    ]
